name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install needed prerequisites
      run: sudo apt-get -y install byacc
      
    - name: cleanup
      run: make cleanup
    - name: build
      run: make
